version: 1.0.{build}
image: Ubuntu
install:
- sh: >-
    . ./git_versioning.sh

        export APP_VERSION=${version}
        export FILE_VERSION=${fileVersion}
        export INFORMATIONAL_VERSION=${informationVersion}

        echo "exported app version is $APP_VERSION"
        echo "exported file version is $FILE_VERSION"
        echo "exported info version is $INFORMATIONAL_VERSION"
- ps: Update-AppveyorBuild -Version "$env:APP_VERSION-build$env:APPVEYOR_BUILD_NUMBER"
build_script:
- sh: >-
    dotnet build Buxfer.sln /p:Version=$APP_VERSION /p:FileVersion=$FILE_VERSION /p:InformationVersion="$INFORMATIONAL_VERSION"  -c Release -v Quiet

    dotnet pack Buxfer.sln -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:PackageVersion=$APP_VERSION /p:Version=$APP_VERSION /p:FileVersion=$FILE_VERSION /p:InformationVersion="$INFORMATIONAL_VERSION"  -c Release -v Quiet  --no-build
test_script:
- sh: dotnet test --filter FullyQualifiedName\!~Login_ValidCredentials_Authenticated_And_returns_Token --logger:Appveyor || 0
artifacts:
- path: '**\Buxfer.*.nupkg'
  name: Packages
- path: '**\Buxfer.*.snupkg'
  name: Symbols
deploy:
- provider: Environment
  name: nuget.org
